export const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export enum Endpoints {
	GET_SESSION = "/api/auth/get-session",
	REGISTER = "/api/auth/register",
	SEND_TEAM_MAIL = "/api/admin/send-team-mail",
	LOGIN = "/api/auth/login",
	LOGOUT = "/api/auth/logout",
	VERIFY_EMAIL = "/api/auth/verify-email",
	SEND_VERIFICATION_EMAIL = "/api/auth/send-verification-mail",
	FORGOT_PASSWORD = "/api/auth/forgot-password",
	ME = "/api/auth/me",
	RESET_PASSWORD = "/api/auth/reset-password",
	GET_TEAM = "/api/team/get",
	CREATE_TEAM = "/api/team/create",
	LEAVE_TEAM = "/api/team/leave",
	DELETE_TEAM = "/api/team/delete",
	LIST_USERS = "/api/auth/list-users",
	LIST_TEAMS = "/api/team/list",
	INVITE_USER = "/api/invite/invite-user",
	SEND_JOIN_REQUEST = "/api/invite/send-join-request",
	ACCEPT_JOIN_REQUEST = "/api/invite/accept-join-request",
	REJECT_JOIN_REQUEST = "/api/invite/reject-join-request",
	LIST_INVITES = "/api/invite/list-invites",
	ACCEPT_INVITE = "/api/invite/accept-invite",
	CANCEL_INVITE = "/api/invite/cancel-invite",
	REJECT_INVITE = "/api/invite/reject-invite",
	CANCEL_JOIN_REQUEST = "/api/invite/cancel-join-request",
	TEAM_INVITES = "/api/invite/my-team-invites",
	REMOVE_MEMBER = "/api/team/remove-member",
	GET_PROGRESS = "/api/team/get-progress",
	GET_ADMIN_PROG = "/api/admin/get-team-prog",
	GET_STAGES = "/api/team/get-stages",
	MAKE_JUDGE = "/api/admin/make-judge",
	CONTACT = "/api/ticket/create",
	MAKE_SUBMISSION = "/api/team/make-submission",
	GET_PROBLEMS = "/api/problem/list",
	GET_SUBMISSION = "/api/team/get-submission",
	DELETE_SUBMISSION = "/api/team/delete-submission",
	GET_PROBLEM = "/api/problem/get",
	APPROVE = "/api/judge/approve",
	REJECT = "/api/judge/reject",
	SUBMISSIONS = "/api/judge/submissions",
	TEAM = "/api/judge/team",
	PROB = "/api/judge/prob",
	TICKETS = "api/ticket/list",
	UPDATE = "api/ticket/update",
	DTEAM = "/api/admin/delete-team",
	ADMIN_SUBMISSIONS = "/api/admin/submissions",
	ADMIN_APPROVE = "/api/admin/admin-approve",
	ADMIN_REJECT = "/api/admin/admin-reject",
	ADMIN_TEAM = "/api/admin/team",
	ADMIN_PROB = "/api/admin/prob",
	SEND_ADMIN_MESSAGE = "/api/admin/send-message",
	GET_COLLEGES = "/api/college/list",
	GET_HOMEPAGE_STATS = "/api/auth/stats",
	GET_ADMIN_STATS = "/api/admin/stats",
	GET_JUDGES = "/api/admin/judges",
	ASSIGN_PROBLEM = "/api/admin/assign-problem",
	DEASSIGN_PROBLEM = "/api/admin/de-assign-problem",
	GET_HOMEPAGE_LEADERBOARD = "/api/auth/bug_bounty_leaderboard",
	LIST_TEAMS_WITH_BUG_ROUND = "/api/judge/listTeamsWithBugRound",
	UPDATE_BUG_ROUND_SCORE = "/api/judge/updateBugRoundScore",
	APPROVED_TEAMS = "/api/judge/get-all-approved-teams",
	UPDATE_SCORE = "/api/judge/update-score",
	GET_ROUNDS = "/api/judge/get-rounds",
	GET_TEAM_JUDGE_MAPPING = "/api/admin/getTeamJudgeMapping",
	UPDATE_TEAM_DEPLOY_STATUS = "/api/judge/updateTeamDeployStatus",
	GET_AVG_DENOMINATOR_CONFIG = "/api/judge/getAverageDenominatorConfig",
}

export const getEndpoint = (endpoint: Endpoints): string => {
	return `${API_URL}${endpoint}`;
};
